### ISSUE TITLE
Increase text size

### ISSUE THREAD

**Issue by mjcollin** [dsiufl/www.dsiufl.org-2016#3]
The main body text size is smaller than most sites use. A larger size will look more chunky and also increase the space that the limited text (1-2 paragraphs) our site uses for most things takes up. It will also look better on a mobile device.

**Comment by mjcollin** [comment]
On my monitor, the site looks best with the text at 125% larger. Can we start there? See this page for an example of what a lot of text looks like:

http://dsiufl.github.io/www.dsiufl.org-2016//workshops/spark/

**Comment by xiaoyaya** [comment]
Increase the font size of work shop posts from 14 pt to 16 pt by adding a script to force to do so.
Can't overwrite the body font size because other fonts are related. Or we need to start over with customized font size sets. See: http://stackoverflow.com/questions/28678542/how-to-change-bootstraps-global-default-font-size

**Comment by mjcollin** [comment]
Fascinating, I guess let's leave it as is for now. I want to try to get the site up in some form soon. This can be a refinement later.
